# Generated by Django 6.0.5 on 2026-05-09 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('primera', 'Primera División'), ('segunda', 'Segunda División'), ('tercera', 'Tercera División')], default='primera', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.CharField(choices=[('portero', 'Portero'), ('defensa', 'Defensa'), ('mediocampista', 'Mediocampista'), ('delantero', 'Delantero')], max_length=20)),
                ('numero_camiseta', models.PositiveIntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='teams.equipo')),
            ],
        ),
    ]
